Documentation:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Rails/HasAndBelongsToMany:
  Enabled: false
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - Rakefile
    - !ruby/regexp /old_and_unused\.rb$/
